-- ========================================
-- CAMPUS MART - BASELINE DATABASE SCHEMA
-- ========================================
-- Generated from the current validated working schema for fresh installs.
-- This baseline intentionally excludes flyway_schema_history because Flyway manages it.
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `admin_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `admin_id` bigint NOT NULL,
  `action` varchar(100) NOT NULL,
  `target_type` enum('USER','ITEM','SYSTEM') NOT NULL,
  `target_id` bigint DEFAULT NULL,
  `description` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `admin_id` (`admin_id`),
  KEY `idx_admin_logs_date` (`created_at` DESC),
  CONSTRAINT `admin_logs_ibfk_1` FOREIGN KEY (`admin_id`) REFERENCES `students` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `api_rate_limit_windows` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `action_name` varchar(50) NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  `limit_count` int NOT NULL,
  `rate_key` varchar(160) NOT NULL,
  `request_count` int NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `window_minutes` int NOT NULL,
  `window_started_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_ke54lm3w879wucr98i604160h` (`rate_key`),
  KEY `idx_rate_limit_expires_at` (`expires_at`),
  KEY `idx_rate_limit_action` (`action_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `blocked_users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `blocked_id` bigint NOT NULL,
  `blocker_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKsjs9rx68tjx90xii3mctenqul` (`blocker_id`,`blocked_id`),
  KEY `FKa7yxttibwaq9plq2a9y5ejvna` (`blocked_id`),
  CONSTRAINT `FK1erbjrn9ke0ihtklyx4kgjnyj` FOREIGN KEY (`blocker_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FKa7yxttibwaq9plq2a9y5ejvna` FOREIGN KEY (`blocked_id`) REFERENCES `students` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `categories` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `icon` varchar(50) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `chat_rooms` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user1_id` bigint NOT NULL,
  `user2_id` bigint NOT NULL,
  `item_id` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `conversation_item_key` bigint NOT NULL,
  `participant_high_id` bigint NOT NULL,
  `participant_low_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_room` (`user1_id`,`user2_id`,`item_id`),
  KEY `user2_id` (`user2_id`),
  KEY `item_id` (`item_id`),
  KEY `idx_chat_rooms_participants` (`participant_low_id`,`participant_high_id`),
  KEY `idx_chat_rooms_created_at` (`created_at`),
  CONSTRAINT `chat_rooms_ibfk_1` FOREIGN KEY (`user1_id`) REFERENCES `students` (`id`),
  CONSTRAINT `chat_rooms_ibfk_2` FOREIGN KEY (`user2_id`) REFERENCES `students` (`id`),
  CONSTRAINT `chat_rooms_ibfk_3` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `commission_ledger_entries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `entry_type` enum('FEE_ESTIMATE','ESCROW_HOLD','RELEASED','REFUNDED','CANCELLED','DISPUTED') NOT NULL,
  `fee_percent` decimal(5,2) NOT NULL,
  `gross_amount` decimal(10,2) NOT NULL,
  `notes` text,
  `platform_fee_amount` decimal(10,2) NOT NULL,
  `seller_net_amount` decimal(10,2) NOT NULL,
  `buyer_id` bigint NOT NULL,
  `item_id` bigint NOT NULL,
  `order_id` bigint NOT NULL,
  `seller_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKifg72qjxsaunfq232si9repac` (`buyer_id`),
  KEY `FKb1boi3rcuk1xvt2p4uacx32i8` (`item_id`),
  KEY `FKhec3xq9uitwhy913oo0upl2kv` (`order_id`),
  KEY `FK8p12wilv9ponxrjismu3lrmf8` (`seller_id`),
  CONSTRAINT `FK8p12wilv9ponxrjismu3lrmf8` FOREIGN KEY (`seller_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FKb1boi3rcuk1xvt2p4uacx32i8` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`),
  CONSTRAINT `FKhec3xq9uitwhy913oo0upl2kv` FOREIGN KEY (`order_id`) REFERENCES `payment_orders` (`id`),
  CONSTRAINT `FKifg72qjxsaunfq232si9repac` FOREIGN KEY (`buyer_id`) REFERENCES `students` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `escrow_events` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `event_type` enum('ORDER_CREATED','PAYMENT_RECEIVED','DELIVERY_CONFIRMED','ESCROW_RELEASED','DISPUTE_RAISED','DISPUTE_RESOLVED','REFUND_INITIATED','REFUND_DONE') DEFAULT NULL,
  `triggered_by` bigint DEFAULT NULL,
  `order_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKf5o6lm3beinwacppqhh6d9o9j` (`order_id`),
  CONSTRAINT `FKf5o6lm3beinwacppqhh6d9o9j` FOREIGN KEY (`order_id`) REFERENCES `payment_orders` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `institutions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `board_or_university` varchar(255) DEFAULT NULL,
  `campus_name` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `country_name` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `institution_type` enum('SCHOOL','COLLEGE','UNIVERSITY','COACHING','OTHER') NOT NULL,
  `is_active` bit(1) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `state_name` varchar(255) DEFAULT NULL,
  `verified` bit(1) DEFAULT NULL,
  `website` varchar(255) DEFAULT NULL,
  `unique_key` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_eyryyuvgsquh7xwidi7mw5w0w` (`unique_key`),
  UNIQUE KEY `uk_institutions_unique_key` (`unique_key`),
  KEY `idx_institutions_search` (`institution_type`,`city`,`state_name`,`verified`,`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `item_images` (
  `item_id` bigint NOT NULL,
  `image_url` longtext NOT NULL,
  KEY `item_id` (`item_id`),
  CONSTRAINT `item_images_ibfk_1` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `title` varchar(200) NOT NULL,
  `description` text,
  `price` decimal(38,2) NOT NULL,
  `photo_url` varchar(255) DEFAULT NULL,
  `status` enum('AVAILABLE','SOLD','RESERVED') DEFAULT NULL,
  `category_id` bigint DEFAULT NULL,
  `seller_id` bigint DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `item_condition` enum('NEW','LIKE_NEW','GOOD','FAIR','POOR') DEFAULT 'GOOD',
  `negotiable` tinyint(1) DEFAULT '0',
  `view_count` int DEFAULT '0',
  `reserved_by` bigint DEFAULT NULL,
  `academic_course` varchar(255) DEFAULT NULL,
  `academic_level` varchar(255) DEFAULT NULL,
  `academic_subject` varchar(255) DEFAULT NULL,
  `board_or_university` varchar(255) DEFAULT NULL,
  `book_author` varchar(255) DEFAULT NULL,
  `book_edition` varchar(255) DEFAULT NULL,
  `boost_expires_at` datetime(6) DEFAULT NULL,
  `boost_level` int DEFAULT NULL,
  `boosted_at` datetime(6) DEFAULT NULL,
  `is_bundle` bit(1) DEFAULT NULL,
  `bundle_size` int DEFAULT NULL,
  `is_donation` bit(1) DEFAULT NULL,
  `isbn` varchar(255) DEFAULT NULL,
  `listing_type` enum('GENERAL','BOOK','DONATION') DEFAULT NULL,
  `publisher` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKq48qocshbmrstbg9b0wf9byio` (`reserved_by`),
  KEY `idx_seller_status` (`seller_id`,`status`),
  KEY `idx_items_status_created_at` (`status`,`created_at`),
  KEY `idx_items_category_status` (`category_id`,`status`),
  KEY `idx_items_seller_created_at` (`seller_id`,`created_at`),
  KEY `idx_items_listing_type_status` (`listing_type`,`status`),
  KEY `idx_items_price` (`price`),
  KEY `idx_items_condition` (`item_condition`),
  KEY `idx_items_boost_expires_at` (`boost_expires_at`),
  KEY `idx_items_created_at` (`created_at`),
  CONSTRAINT `FKq48qocshbmrstbg9b0wf9byio` FOREIGN KEY (`reserved_by`) REFERENCES `students` (`id`),
  CONSTRAINT `items_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`),
  CONSTRAINT `items_ibfk_2` FOREIGN KEY (`seller_id`) REFERENCES `students` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `messages` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `sender_id` bigint NOT NULL,
  `receiver_id` bigint NOT NULL,
  `item_id` bigint DEFAULT NULL,
  `content` text NOT NULL,
  `is_read` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_messages_sender` (`sender_id`),
  KEY `idx_messages_receiver` (`receiver_id`),
  KEY `idx_messages_item` (`item_id`),
  KEY `idx_messages_created` (`created_at` DESC),
  CONSTRAINT `messages_ibfk_1` FOREIGN KEY (`sender_id`) REFERENCES `students` (`id`),
  CONSTRAINT `messages_ibfk_2` FOREIGN KEY (`receiver_id`) REFERENCES `students` (`id`),
  CONSTRAINT `messages_ibfk_3` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `notification_entries` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `body` varchar(255) NOT NULL,
  `click_action` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `is_read` bit(1) DEFAULT NULL,
  `title` varchar(255) NOT NULL,
  `type_name` varchar(255) NOT NULL,
  `student_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK11xdomoc5ca8svp4731ou2836` (`student_id`),
  CONSTRAINT `FK11xdomoc5ca8svp4731ou2836` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `offers` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `note` text,
  `offered_price` double NOT NULL,
  `status` enum('PENDING','ACCEPTED','REJECTED') NOT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `buyer_id` bigint NOT NULL,
  `item_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK3yjigdaccqkpgwqy8j6d136t9` (`buyer_id`),
  KEY `FK89puwr57fgtijk7jlsbp8bmiv` (`item_id`),
  CONSTRAINT `FK3yjigdaccqkpgwqy8j6d136t9` FOREIGN KEY (`buyer_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FK89puwr57fgtijk7jlsbp8bmiv` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `otp_rate_limits` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `identifier` varchar(255) NOT NULL,
  `otp_type` enum('EMAIL','PHONE') NOT NULL,
  `send_count` int DEFAULT '1',
  `window_start` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_identifier` (`identifier`,`otp_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `otp_sessions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `attempts` int DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `expires_at` datetime(6) DEFAULT NULL,
  `is_used` bit(1) DEFAULT NULL,
  `otp_code` varchar(255) NOT NULL,
  `otp_type` enum('EMAIL','PHONE') DEFAULT NULL,
  `session_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKcva4g1j6kehhklvfobs3fomg9` (`session_id`),
  CONSTRAINT `FKcva4g1j6kehhklvfobs3fomg9` FOREIGN KEY (`session_id`) REFERENCES `registration_sessions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `otp_verifications` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `user_id` bigint NOT NULL,
  `otp_code` varchar(6) NOT NULL,
  `otp_type` enum('EMAIL','PHONE') NOT NULL,
  `expires_at` datetime NOT NULL,
  `is_used` tinyint(1) DEFAULT '0',
  `attempts` int DEFAULT '0',
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  CONSTRAINT `otp_verifications_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `students` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `otps` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `email` varchar(255) NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  `otp` varchar(255) NOT NULL,
  `verified` bit(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `payment_orders` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `amount` decimal(38,2) NOT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `currency` varchar(255) DEFAULT NULL,
  `escrow_released` bit(1) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `payment_method` varchar(255) DEFAULT NULL,
  `razorpay_order_id` varchar(255) NOT NULL,
  `razorpay_payment_id` varchar(255) DEFAULT NULL,
  `razorpay_signature` varchar(255) DEFAULT NULL,
  `release_deadline` datetime(6) DEFAULT NULL,
  `status` enum('CREATED','PAID','FAILED','REFUNDED','ESCROW_HOLD','RELEASED','DISPUTED') DEFAULT NULL,
  `updated_at` datetime(6) DEFAULT NULL,
  `buyer_id` bigint NOT NULL,
  `item_id` bigint NOT NULL,
  `seller_id` bigint NOT NULL,
  `platform_fee_amount` decimal(10,2) DEFAULT NULL,
  `platform_fee_percent` decimal(5,2) DEFAULT NULL,
  `seller_net_amount` decimal(10,2) DEFAULT NULL,
  `seller_subscription_code` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_3crv9wke92o3hwlgsulh5xses` (`razorpay_order_id`),
  KEY `FK19k5du5ii6mtk9t6dqkf93r0j` (`buyer_id`),
  KEY `FKmny6cvat4pyg0s1fkgudh7o51` (`item_id`),
  KEY `FKe6vmvjgphmorv68p1qhp7cw9g` (`seller_id`),
  CONSTRAINT `FK19k5du5ii6mtk9t6dqkf93r0j` FOREIGN KEY (`buyer_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FKe6vmvjgphmorv68p1qhp7cw9g` FOREIGN KEY (`seller_id`) REFERENCES `students` (`id`),
  CONSTRAINT `FKmny6cvat4pyg0s1fkgudh7o51` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `refresh_token_sessions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `email` varchar(255) NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  `last_used_at` datetime(6) DEFAULT NULL,
  `replaced_by_jti` varchar(64) DEFAULT NULL,
  `revoked_at` datetime(6) DEFAULT NULL,
  `session_version` int NOT NULL,
  `token_jti` varchar(64) NOT NULL,
  `user_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_2duodu2jf0pk1tww7lyfmjxvn` (`token_jti`),
  KEY `idx_refresh_token_user_id` (`user_id`),
  KEY `idx_refresh_token_expires_at` (`expires_at`),
  KEY `idx_refresh_token_revoked_at` (`revoked_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `registration_sessions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `email_verified` bit(1) DEFAULT NULL,
  `expires_at` datetime(6) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `phone` varchar(255) NOT NULL,
  `phone_verified` bit(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_qhm617bl79un7q8rlng1dhr79` (`email`),
  UNIQUE KEY `UK_bf7whbuwc1xnaqm6nr9l4ps12` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `reports` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `reporter_id` bigint NOT NULL,
  `item_id` bigint NOT NULL,
  `reason` enum('FAKE_ITEM','WRONG_PRICE','SPAM','INAPPROPRIATE','ALREADY_SOLD','OTHER') NOT NULL,
  `description` text,
  `status` enum('PENDING','REVIEWED','DISMISSED') DEFAULT 'PENDING',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `resolution_note` text,
  `reviewed_at` datetime(6) DEFAULT NULL,
  `reviewed_by` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `one_report` (`reporter_id`,`item_id`),
  KEY `item_id` (`item_id`),
  KEY `idx_reports_status` (`status`),
  KEY `FKct12r04qndw5tolls0xum4jyr` (`reviewed_by`),
  CONSTRAINT `FKct12r04qndw5tolls0xum4jyr` FOREIGN KEY (`reviewed_by`) REFERENCES `students` (`id`),
  CONSTRAINT `reports_ibfk_1` FOREIGN KEY (`reporter_id`) REFERENCES `students` (`id`),
  CONSTRAINT `reports_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `reviews` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `reviewer_id` bigint NOT NULL,
  `seller_id` bigint NOT NULL,
  `item_id` bigint NOT NULL,
  `rating` int NOT NULL,
  `comment` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_review` (`reviewer_id`,`item_id`),
  KEY `seller_id` (`seller_id`),
  KEY `item_id` (`item_id`),
  CONSTRAINT `reviews_ibfk_1` FOREIGN KEY (`reviewer_id`) REFERENCES `students` (`id`) ON DELETE CASCADE,
  CONSTRAINT `reviews_ibfk_2` FOREIGN KEY (`seller_id`) REFERENCES `students` (`id`) ON DELETE CASCADE,
  CONSTRAINT `reviews_ibfk_3` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`) ON DELETE CASCADE,
  CONSTRAINT `reviews_chk_1` CHECK ((`rating` between 1 and 5))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `security_audit_logs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `details` varchar(500) DEFAULT NULL,
  `event_type` varchar(64) NOT NULL,
  `ip_address_masked` varchar(64) DEFAULT NULL,
  `student_id` bigint DEFAULT NULL,
  `success` bit(1) NOT NULL,
  `user_agent` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_security_audit_created_at` (`created_at`),
  KEY `idx_security_audit_student_event` (`student_id`,`event_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `site_settings` (
  `id` bigint NOT NULL,
  `about_summary` tinytext,
  `business_email` varchar(255) DEFAULT NULL,
  `company_name` varchar(255) DEFAULT NULL,
  `company_tagline` varchar(255) DEFAULT NULL,
  `cookie_policy_content` tinytext,
  `disclaimer_content` tinytext,
  `github_url` varchar(255) DEFAULT NULL,
  `instagram_url` varchar(255) DEFAULT NULL,
  `linkedin_url` varchar(255) DEFAULT NULL,
  `office_address` tinytext,
  `privacy_policy_content` tinytext,
  `refund_policy_content` tinytext,
  `support_email` varchar(255) DEFAULT NULL,
  `support_hours` varchar(255) DEFAULT NULL,
  `support_whatsapp_number` varchar(255) DEFAULT NULL,
  `terms_content` tinytext,
  `x_url` varchar(255) DEFAULT NULL,
  `youtube_url` varchar(255) DEFAULT NULL,
  `cart_logo_url` tinytext,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `student_fcm_tokens` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `fcm_token` text NOT NULL,
  `platform` varchar(255) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `student_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK16vy0pc9iguadixdh1o8xt09` (`student_id`),
  CONSTRAINT `FK16vy0pc9iguadixdh1o8xt09` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `students` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(255) NOT NULL,
  `phone` varchar(15) DEFAULT NULL,
  `branch` varchar(100) DEFAULT NULL,
  `hostel` varchar(100) DEFAULT NULL,
  `college_id` varchar(50) DEFAULT NULL,
  `profile_pic` longtext,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `bio` text,
  `email_verified` tinyint(1) DEFAULT '0',
  `phone_verified` tinyint(1) DEFAULT '0',
  `is_active` tinyint(1) DEFAULT '0',
  `login_attempts` int DEFAULT '0',
  `locked_until` datetime DEFAULT NULL,
  `google_id` varchar(255) DEFAULT NULL,
  `facebook_id` varchar(255) DEFAULT NULL,
  `auth_provider` enum('LOCAL','GOOGLE','FACEBOOK') DEFAULT 'LOCAL',
  `device_token` text,
  `role` enum('STUDENT','MODERATOR','ADMIN') DEFAULT 'STUDENT',
  `is_banned` tinyint(1) DEFAULT '0',
  `ban_reason` text,
  `banned_at` timestamp NULL DEFAULT NULL,
  `device_platform` varchar(255) DEFAULT NULL,
  `allow_direct_chat` bit(1) DEFAULT NULL,
  `email_notifications_enabled` bit(1) DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `location_label` varchar(255) DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `preferred_language` varchar(255) DEFAULT NULL,
  `privacy_mode` varchar(255) DEFAULT NULL,
  `push_notifications_enabled` bit(1) DEFAULT NULL,
  `show_phone_on_listings` bit(1) DEFAULT NULL,
  `campus_name` varchar(255) DEFAULT NULL,
  `city` varchar(255) DEFAULT NULL,
  `class_level` varchar(255) DEFAULT NULL,
  `country_name` varchar(255) DEFAULT NULL,
  `course_name` varchar(255) DEFAULT NULL,
  `institution_name` varchar(255) DEFAULT NULL,
  `institution_type` enum('SCHOOL','COLLEGE','UNIVERSITY','COACHING','OTHER') DEFAULT NULL,
  `state_name` varchar(255) DEFAULT NULL,
  `institution_id` bigint DEFAULT NULL,
  `active_subscription_code` varchar(255) DEFAULT NULL,
  `available_boost_credits` int DEFAULT NULL,
  `contact_access_expires_at` datetime(6) DEFAULT NULL,
  `contact_access_tier` enum('FREE','PLUS','PREMIUM') DEFAULT NULL,
  `current_commission_percent` decimal(5,2) DEFAULT NULL,
  `moderation_strike_count` int DEFAULT NULL,
  `subscription_activated_at` datetime(6) DEFAULT NULL,
  `used_boost_credits` int DEFAULT NULL,
  `auth_session_version` int DEFAULT NULL,
  `last_login_at` datetime(6) DEFAULT NULL,
  `last_login_ip` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`),
  UNIQUE KEY `uk_students_phone` (`phone`),
  KEY `idx_students_role` (`role`),
  KEY `idx_students_banned` (`is_banned`),
  KEY `idx_students_hostel` (`hostel`),
  KEY `idx_students_branch` (`branch`),
  KEY `idx_students_lat_lng` (`latitude`,`longitude`),
  KEY `idx_students_institution_id` (`institution_id`),
  CONSTRAINT `FKhu5lxwgdn4ab5bf49h5s10iu5` FOREIGN KEY (`institution_id`) REFERENCES `institutions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `subscription_records` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `amount` decimal(10,2) NOT NULL,
  `commission_percent` decimal(5,2) NOT NULL,
  `expires_at` datetime(6) DEFAULT NULL,
  `included_boost_credits` int DEFAULT NULL,
  `notes` text,
  `payment_mode` enum('TEST','LIVE') NOT NULL,
  `plan_code` varchar(255) NOT NULL,
  `plan_name` varchar(255) NOT NULL,
  `started_at` datetime(6) NOT NULL,
  `status` enum('ACTIVE','EXPIRED','CANCELLED') NOT NULL,
  `student_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK880hk5hw7819qlv9b8nw8y1as` (`student_id`),
  CONSTRAINT `FK880hk5hw7819qlv9b8nw8y1as` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `support_requests` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `app_platform` varchar(255) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `created_at` datetime(6) DEFAULT NULL,
  `email` varchar(255) NOT NULL,
  `message` text,
  `name` varchar(255) NOT NULL,
  `page_path` varchar(255) DEFAULT NULL,
  `resolved_at` datetime(6) DEFAULT NULL,
  `status` enum('OPEN','IN_PROGRESS','RESOLVED') NOT NULL,
  `subject` varchar(255) DEFAULT NULL,
  `type` enum('FEEDBACK','PROBLEM_REPORT','CONTACT') NOT NULL,
  `student_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKotprq3dsdg97g6yaegdj42wep` (`student_id`),
  CONSTRAINT `FKotprq3dsdg97g6yaegdj42wep` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `transactions` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `buyer_id` bigint NOT NULL,
  `seller_id` bigint NOT NULL,
  `item_id` bigint NOT NULL,
  `amount` decimal(38,2) DEFAULT NULL,
  `status` enum('COMPLETED','PENDING','CANCELLED') DEFAULT 'COMPLETED',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `buyer_id` (`buyer_id`),
  KEY `seller_id` (`seller_id`),
  KEY `item_id` (`item_id`),
  CONSTRAINT `transactions_ibfk_1` FOREIGN KEY (`buyer_id`) REFERENCES `students` (`id`) ON DELETE CASCADE,
  CONSTRAINT `transactions_ibfk_2` FOREIGN KEY (`seller_id`) REFERENCES `students` (`id`) ON DELETE CASCADE,
  CONSTRAINT `transactions_ibfk_3` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `wishlists` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `student_id` bigint NOT NULL,
  `item_id` bigint NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_wishlist` (`student_id`,`item_id`),
  UNIQUE KEY `uk_wishlists_student_item` (`student_id`,`item_id`),
  KEY `idx_wishlists_student_created_at` (`student_id`,`created_at`),
  KEY `idx_wishlists_item` (`item_id`),
  CONSTRAINT `wishlists_ibfk_1` FOREIGN KEY (`student_id`) REFERENCES `students` (`id`) ON DELETE CASCADE,
  CONSTRAINT `wishlists_ibfk_2` FOREIGN KEY (`item_id`) REFERENCES `items` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
